// Dynamic config layered over app.json. Expo reads this file when it exists and hands
// the static app.json config in as `config` — so app.json stays the place for everything
// that doesn't need computing, and this file only adds what does.
//
// It exists for one value: the commit the bundle was built from. The server deploys by
// pulling main and re-running `expo export` (pull-and-restart.sh), so a build that failed
// or never ran is invisible from the outside — production looks fine, it's just old. The
// hash is stamped in here, at export time, and shown in the dev rail's title.
//
// This runs in the bundler's node process on the build machine, not in the app, so
// shelling out to git is fine — but it's also the reason the value is frozen at build
// time: committing after `expo start` won't change what a running dev server reports.

const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const git = (args) =>
  execSync(`git ${args}`, {
    cwd: __dirname,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  }).trim();

// Short hash, marked +dirty when the working tree doesn't match it — locally that's the
// normal state, and it's the honest answer to "which code is this?" when the answer is
// "this commit plus uncommitted edits".
//
// Never throws: a build from a tarball or a shallow copy with no .git is a working build,
// and losing the version label is not a reason to fail the export.
const codeVersion = () => {
  try {
    const hash = git('rev-parse --short HEAD');
    const dirty = git('status --porcelain') !== '';
    return dirty ? `${hash}+dirty` : hash;
  } catch {
    return 'nogit';
  }
};

// Where the version reaches the app from. Generated rather than passed through config or
// environment, because neither survives the trip on both sides:
//
//   • `extra` + expo-constants — on web, expo-constants reads the manifest out of
//     process.env.APP_MANIFEST, which this configuration doesn't inline. Constants
//     .expoConfig is empty in the browser and in the server bundle alike.
//   • process.env.EXPO_PUBLIC_CODE_VERSION — babel substitutes it into the *client*
//     bundle, but leaves it as a live process.env lookup in the *server* bundle. A
//     deployed API route would then read pm2's environment, not the build, and answer
//     'unknown' — or worse, answer with whatever the running process was started with,
//     which is exactly the stale-vs-current distinction the value exists to make.
//
// A literal in a generated module has neither problem: it is the same value wherever it
// is bundled. Gitignored and rewritten on every start/export, in the same spirit as the
// generated expo-env.d.ts.
const GENERATED = path.join(__dirname, 'src/lib/code-version.ts');

const writeVersionModule = (version) => {
  const body = `// GENERATED by app.config.js on each expo start/export — do not edit, and do not
// commit: it is rewritten with the working tree's own state every time.
export const CODE_VERSION = ${JSON.stringify(version)};
`;
  // Only write when it actually changed. This file sits inside src/, so an unconditional
  // write would touch it on every start and hand Metro a spurious change to rebuild.
  try {
    if (fs.readFileSync(GENERATED, 'utf8') === body) return;
  } catch { /* not there yet — fall through and create it */ }
  fs.writeFileSync(GENERATED, body);
};

module.exports = ({ config }) => {
  // An explicit value wins, so a CI build number can be supplied instead of a hash.
  const version = process.env.EXPO_PUBLIC_CODE_VERSION || codeVersion();
  writeVersionModule(version);

  return {
    ...config,
    // Also on the config itself, where `expo config` and any native build can read it.
    extra: { ...config.extra, codeVersion: version },
  };
};
